import { assertStrictEquals } from "./deps.ts";
import { ArrayBufferViewConstructor } from "../mod.ts";

Deno.test("ArrayBufferViewConstructor.isDataViewConstructor(*)", () => {
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Uint8Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Uint8ClampedArray),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Int8Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Uint16Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Int16Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Uint32Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Int32Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Float32Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Float64Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(BigUint64Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(BigInt64Array),
    false,
  );

  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(DataView),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(null),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isDataViewConstructor(new Uint8Array(0)),
    false,
  );
});

Deno.test("ArrayBufferViewConstructor.isArrayBufferViewConstructor(*)", () => {
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Uint8Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Uint8ClampedArray),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Int8Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Uint16Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Int16Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Uint32Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Int32Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Float32Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Float64Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(BigUint64Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(BigInt64Array),
    true,
  );

  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(DataView),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(null),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isArrayBufferViewConstructor(new Uint8Array(0)),
    false,
  );
});

Deno.test("ArrayBufferViewConstructor.isTypedArrayConstructor(*)", () => {
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Uint8Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Uint8ClampedArray),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Int8Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Uint16Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Int16Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Uint32Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Int32Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Float32Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Float64Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(BigUint64Array),
    true,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(BigInt64Array),
    true,
  );

  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(DataView),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(Array),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(null),
    false,
  );
  assertStrictEquals(
    ArrayBufferViewConstructor.isTypedArrayConstructor(new Uint8Array(0)),
    false,
  );
});
